#! /bin/zsh

# TODO: make sure user is in appropriate group 
if [[ $EUID -eq 0 ]]; then
    echo "This program should not be run as root."
    exit 1
fi

print -n "Enter username: "
read user
if [[ -n $(cat /etc/passwd | grep ^${user}:) ]]; then
    print "user $user already exists"
    exit 1
fi

print -n "Enter phone: "
read phone

pass=$(< /dev/urandom tr -dc 0-9 | head -c${1:-6})
sudo useradd -m $user
sudo chpasswd <<< $user:$pass

sudo su $user -s /bin/zsh <<EOF
ssh-keygen -q -t rsa -N '' -f \$HOME/.ssh/id_rsa <<< y 
EOF

echo I am $USER
# temporary. should assume script is in /usr/local/bin
./bin/dlp-sendsms $phone "Your Linux password: $pass"

pubkey=$(sudo cat /home/$user/.ssh/id_rsa.pub)
for host in $(cat etc/hosts | cut -d':' -f2); do
    (
    ssh $host /bin/zsh <<EOF
    sudo /usr/sbin/useradd -m $user
    sudo /usr/sbin/chpasswd <<< "$user:$pass"
    sudo mkdir /home/$user/.ssh
    sudo zsh <<< 'print $pubkey >> /home/$user/.ssh/authorized_keys'
    sudo chown $user:$user /home/$user/.ssh/authorized_keys
    sudo chmod 600 /home/$user/.ssh/authorized_keys
    sudo chown $user:$user /home/$user/.ssh
    sudo chmod 700 /home/$user/.ssh
EOF
    ) &
done

sudo passwd -e $user
